[package]
name = "shiitake-rs"
edition.workspace = true
version.workspace = true

[dependencies]
shiitake-server-api = { path = "../../shiitake-server-api" }
reqwest = { version = "0.13", default-features = false, features = [
    "json",
    "rustls-no-provider",
] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
webpki-roots = "1"
thiserror = "2"
